server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: api_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: search_api
          __path__: /var/log/app/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            trace_id: trace_id
            span_id: span_id
            request_id: request_id
            path: path
            method: method
            status_code: status_code
            latency_ms: latency_ms
      - labels:
          trace_id:
          span_id:
          request_id:
          path:
          method:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339