global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "search-api"
    scrape_interval: 5s
    static_configs:
      - targets: ["api:8000"]

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
